name: cafri
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  universal_html: ^2.2.4
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  table_calendar: ^3.2.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.2
  geocoding: ^4.0.0
  firebase_messaging: ^15.2.7
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.6
  firebase_storage: ^12.4.7
  share_plus: ^11.0.0
  signature: ^6.3.0
  pdf: ^3.11.3
  path_provider: ^2.1.5
  font_awesome_flutter: ^10.3.0
  printing: ^5.14.2
  open_file: ^3.2.1
  flutter_launcher_icons: ^0.14.4
  logger: ^2.6.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  geolocator: ^11.0.0
  workmanager: ^0.8.0
  flutter_foreground_task: ^9.1.0
  flutter_polyline_points: ^2.1.0
  http: ^1.5.0-beta.2
  flutter_compass: ^0.8.1
  csv: ^6.0.0
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

# --- Agrega esta sección para configurar los íconos de la app ---
flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"